### ISSUE TITLE
Test fails, can't find @bumaga/tabs

### ISSUE THREAD

**Issue by LiteSoul** [jeetiss/tabs#5]
If I use a new Create React App, then use this library, the CRA Jest test fails:
`Cannot find module '@bumaga/tabs' from 'SomeComponent.js'`

If I change the import to a more explicit:
`import { Tabs, useTabState, Panel } from "@bumaga/tabs/dis/index";`
It also fails, but with a different error.

What could this be?

**Comment by thisgeek** [comment]
Looks related to #2.

**Comment by jeetiss** [comment]
yep, I see what the problem is.

Need setup rollbar and babel for transpiling imports to commonjs. Did you wanna help?

**Comment by LiteSoul** [comment]
Ah, could be. You can test by just using CRA, then using the library and some test on any component, example:

`//  App.test.js
import React from "react";
import ReactDOM from "react-dom";
import App from "./App";

it("renders without crashing", () => {
  const div = document.createElement("div");
  ReactDOM.render(<App />, div);
  ReactDOM.unmountComponentAtNode(div);
});
`

**Comment by jeetiss** [comment]
Yep, thanks
I made repo with [test case](https://github.com/jeetiss/test-tabs)

test fails because jest don't [compile](https://jestjs.io/docs/en/configuration#transformignorepatterns-array-string)  `node_modules` on default, with this library I provide es6 code with imports, and it main reason for errors

to fix this error need setup rollup with 2 targets (esm and cjs) and change main field in `package.json` to bundled cjs file

I can do this later on this week 🙌🏻

**Comment by LiteSoul** [comment]
Sure, no hurry, thanks! Fantastic little library, it's really fast.

**Comment by jeetiss** [comment]
@LiteSoul  Released the new version `v0.1.3` with fix, feel free to upgrade!

**Comment by LiteSoul** [comment]
Working great! Thanks!
